apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: demo-app
    environment: production
spec:
  destination:
    namespace: demo-app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/cyberdine-skynet/skynet-platform.git
    targetRevision: main
    path: manifests/demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
