apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-controller
  namespace: metallb-system
  labels:
    app: metallb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metallb
      component: controller
  template:
    metadata:
      labels:
        app: metallb
        component: controller
    spec:
      automountServiceAccountToken: false
      containers:
        - name: controller
          image: quay.io/metallb/controller:v0.13.12
          args:
            - --port=7472
          ports:
            - containerPort: 7472
          env:
            - name: METALLB_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              storage: "1Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
