# Ultra-fast pre-commit for development
repos:
  - repo: local
    hooks:
      - id: smart-yaml-fix
        name: Smart YAML Auto-fix
        entry: scripts/smart-yaml-hook.sh
        language: script
        files: \.(yaml|yml)$
        pass_filenames: false
      - id: quick-fix
        name: Quick fixes
        entry: scripts/fast-fix.sh
        language: script
        pass_filenames: false
        always_run: true
