# Cert-Manager Helm Values
# Configuration for certificate management in the Skynet platform

# Global settings
global:
  leaderElection:
    namespace: cert-manager
# Main cert-manager controller
replicaCount: 1
image:
  repository: quay.io/jetstack/cert-manager-controller
  pullPolicy: IfNotPresent
# Resource limits
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
# Security settings
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001
# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001
# Service account
serviceAccount:
  create: true
  automountServiceAccountToken: true
# Webhook configuration
webhook:
  replicaCount: 1
  timeoutSeconds: 10
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
# CA Injector
cainjector:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
# Monitoring
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
    prometheusInstance: default
    targetPort: 9402
    path: /metrics
    interval: 60s
    scrapeTimeout: 30s
# Additional configuration
extraArgs: []
# Node selector for scheduling
nodeSelector: {}
# Tolerations
tolerations: []
# Affinity rules
affinity: {}
# Install CRDs
installCRDs: true
