apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mkdocs-docs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cyberdine-skynet/skynet-platform
    targetRevision: main
    path: manifests/mkdocs-docs
  destination:
    server: https://kubernetes.default.svc
    namespace: docs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
