apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skynet-root-app-of-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: skynet-platform
    app.kubernetes.io/component: root-app
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/cyberdine-skynet/skynet-platform
    targetRevision: main
    path: apps
    directory:
      recurse: true
      exclude: |
        root-app.yaml
        */manifests/**
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
