apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mkdocs-docs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: mkdocs-docs
    app.kubernetes.io/component: documentation
spec:
  destination:
    namespace: docs
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/cyberdine-skynet/skynet-platform.git
    targetRevision: HEAD
    path: manifests/mkdocs-docs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 10
