# Cert-Manager Cluster Issuers
# IMPORTANT: Update email address and configure for your domain/environment

# Let's Encrypt Production Issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app.kubernetes.io/name: cert-manager-issuers
    app.kubernetes.io/component: security
spec:
  acme:
    # IMPORTANT: Replace with your email address
    email: admin@example.com # UPDATE THIS EMAIL
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    # HTTP01 challenge solver for simple domains
    solvers:
      - http01:
          ingress:
            class: nginx # Will use NGINX ingress controller
---
# Let's Encrypt Staging Issuer (for testing)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app.kubernetes.io/name: cert-manager-issuers
    app.kubernetes.io/component: security
spec:
  acme:
    # IMPORTANT: Replace with your email address
    email: admin@example.com # UPDATE THIS EMAIL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-private-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
# Self-Signed Issuer (for internal/development certificates)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  labels:
    app.kubernetes.io/name: cert-manager-issuers
    app.kubernetes.io/component: security
spec:
  selfSigned: {}
