apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.fle.api64.de:30443
  application.instanceLabelKey: argocd.argoproj.io/instance
  server.rbac.log.enforce.enable: "true"
  exec.enabled: "false"
  admin.enabled: "true"
  timeout.hard.reconciliation: "0"
  timeout.reconciliation: "180s"
  # Server configuration for insecure access (via Traefik proxy)
  server.insecure: "true"
  # GitHub OAuth disabled - use local admin account for now
  # dex.config: "connectors:\n  - type: github\n    id: github\n    name: GitHub\n    config:\n      clientID: Ov23liD7vhKxvYHgF1WE\n      clientSecret: 11630d854dd2d4bf9a46572e8e81575ba8a0d6c5\n      orgs:\n        - name: cyberdine-skynet\n          teams:\n            - admin\n            - developers\n            - maintainers\n      teamNameField: slug\n      useLoginAsID: false\n      loadAllGroups: false\n      \n"
  # OIDC configuration disabled - use local admin account for now  
  # oidc.config: |
  #   name: GitHub
  #   issuer: https://argocd.fle.api64.de:30543/api/dex
  #   clientId: argo-cd
  #   clientSecret: $oidc.github.clientSecret
  #   requestedScopes: ["openid", "profile", "email", "groups"]
  #   requestedIDTokenClaims: {"groups": {"essential": true}}
