apiVersion: v1
kind: Secret
metadata:
  name: github-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/cyberdine-skynet/skynet-platform
  username: token
  password: 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
