apiVersion: v1
kind: Secret
metadata:
  name: github-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/cyberdine-skynet/skynet-platform
  username: not-used
  password: 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
