apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: gitops
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 6.7.12
    helm:
      valuesObject:
        # Global configuration
        global:
          domain: argocd.fle.api64.de
        # Server configuration with NodePort
        server:
          service:
            type: NodePort
            nodePortHttp: 30180
            nodePortHttps: 30543
          # Additional server configuration
          extraArgs:
            - --insecure
          # Server ingress (optional, can be used alongside NodePort)
          ingress:
            enabled: false
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - argocd.fle.api64.de
            tls:
              - secretName: argocd-server-tls
                hosts:
                  - argocd.fle.api64.de
        # Repository server configuration
        repoServer:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
        # Application controller configuration
        controller:
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
        # Redis configuration
        redis:
          enabled: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
        # Dex (OIDC) configuration - ready for GitHub SSO
        dex:
          enabled: true
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
        # Configuration management
        configs:
          params:
            server.insecure: false
            controller.diff.server.side: true
            server.grpc.web: true
            # Repository credentials are managed by separate secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 10
