apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    # Force HTTPS redirect
    traefik.ingress.kubernetes.io/redirect-scheme: https
    # Handle gRPC traffic for Argo CD
    traefik.ingress.kubernetes.io/router.middlewares: argocd-server-grpc@kubernetescrd
spec:
  tls:
    - hosts:
        - argocd.fle.api64.de
      secretName: argocd-server-tls
  rules:
    - host: argocd.fle.api64.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: argocd-server-grpc
  namespace: argocd
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
    customResponseHeaders:
      X-Frame-Options: "SAMEORIGIN"
      X-Content-Type-Options: "nosniff"
