# Argo CD Helm Values
# This file can be used to override specific values for the Argo CD deployment

# Global settings
global:
  domain: argocd.fle.api64.de
# Server configuration
server:
  # Service configuration
  service:
    type: ClusterIP
  # Server arguments
  extraArgs:
    - --insecure # Remove this in production and use proper TLS
  # Resource limits
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
# High availability settings (for production)
ha:
  enabled: false # Set to true for production deployments
# Monitoring and observability
metrics:
  enabled: true
  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8082"
      prometheus.io/path: "/metrics"
# Notifications (optional)
notifications:
  enabled: false
  # Configure notifications for Slack, Discord, etc.
# Application Set Controller (for advanced GitOps patterns)
applicationSet:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
